# docker-compose.yml
version: '3'

networks:
  postgres:
    driver: bridge

volumes:
  apr-data-test:


services:

  postgres:
    image: postgis/postgis:14-3.3
    container_name: postgreSQL-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r2tadmiadc
      APP_DB_NAME: apr
      PGDATA: /data/postgres
    volumes:
      - ./dev-mount:/docker-entrypoint-initdb.d/
      - ./apr-seeding:/home
      - apr-data-test:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
